### ISSUE TITLE
BBC iPlayer WWW support + a question

### ISSUE THREAD

**Issue by t0mtee** [luizoti/script.library.integration.tool#18]
**Describe the bug**
It would be good to add iPlayer WWW support

**To Reproduce**
This is what currently happens with iPlayer WWW:
1. Go to 'iPlayer WWW' addon
2. Search for a show
3. Click on 'Add selected item to library'
4. See error 'Show could not be identified'

**Expected behavior**
Show gets added to the library

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Kodi Version: 18.9

**Additional context**
[This](https://github.com/luizoti/script.library.integration.tool/archive/refs/heads/Leia.zip) is the right download for the addon, right? I'm not sure if I have the original addon or the forked installed.

**Kodi log**
Provide the kodi log with error:
[kodi.log](https://github.com/luizoti/script.library.integration.tool/files/6751001/kodi.log)

**Comment by luizoti** [comment]
Hey,

1. Is this a free addon? (need a signature?)
2. Is this a pirated addon (an addon that makes the content illegally available)?

If I'm paid, I can't add support without having a subscription.

If it's a pirated addon I won't add support, LIT follows kodi forum guidelines that don't accept piracy: https://forum.kodi.tv/showthread.php?tid=327514&pid=3043341#pid3043341

**Comment by t0mtee** [comment]
Its a free addon, available on the official repo

**Comment by luizoti** [comment]
Good, i Will try to add support in future

**Comment by t0mtee** [comment]
> 
> 
> Good, i Will try to add support in future

could I get an eta?

**Comment by luizoti** [comment]
Problaby in this week.

**Comment by t0mtee** [comment]
> 
> 
> Problaby in this week.

nice, thanks for taking in my suggestion (also thanks for continuing the LIT project, it was a shame to see the dev stop working on it and had to move to Add to Lib, an addon which is several years old and VERY slow)

**Comment by t0mtee** [comment]
Just some more info, I have migrated my entire Kodi build to Matrix, iPlayer is still not supported

**Comment by luizoti** [comment]
This complicates things, I don't intend to release update for kodi 18 anymore, when IPlayer works in Matrix I try to add support.

**Comment by t0mtee** [comment]
> 
> 
> This complicates things, I don't intend to release update for kodi 18 anymore, when IPlayer works in Matrix I try to add support.

This is the reason I migrated to Matrix, slowly I will miss out on addon updates. Also, iPlayer is working in Matrix, I just tried it.

**Comment by t0mtee** [comment]
Oh, I see where the confusion came from now. When I said "iPlayer is still not supported", I meant the LIT didn't work with iPlayer on Matrix. iPlayer itself works fine, LIT doesn't support it.

**Comment by luizoti** [comment]
haaa, ok, if matrix support, i will check.

**Comment by t0mtee** [comment]
lemme know when it's ready and thanks!

**Comment by t0mtee** [comment]
@luizoti hey, how's the support going?

**Comment by luizoti** [comment]
I'm currently trying to optimize a core function of LIT and it's a bit complex, I couldn't work on iplayer. What content did you try to add from iplayer?

**Comment by t0mtee** [comment]
> 
> 
> I'm currently trying to optimize a core function of LIT and it's a bit complex, I couldn't work on iplayer. What content did you try to add from iplayer?

Sorry for late response
I was trying to add Doctor Who

**Comment by luizoti** [comment]
Hi, sorry @OsoaGitHub for the delay, I finally managed to do the tests with the BBC, and I found some problems:

## Problem 1
In the test I did, for example, when opening the dr. who for example instead of showing a list with the folders of the seasons, it shows the episodes of the first season and the folders of the other seasons.
 
### And what's wrong?
I'm going to have to juggle a way to deal with this nonsensical structure, it's probably going to be a bunch of hard code to deal with.

If you really need to watch for this addon, ask the devs to change this behavior.

BBC, example of bad directories: https://imgur.com/NF6G1t9.png
HBO MAX good example: https://imgur.com/RSzqzpM.png

## Problem 2

The way lit works, it needs addons to return some types of data to be processed, I rewrote it to deal as best as possible with the differences, but the idea is that all addons return the same data. follows a bad example from the BBC:

```
    {
        "art": {
            "icon": "image://DefaultFolder.png/",
            "thumb": "image://https%3a%2f%2fichef.bbci.co.uk%2fimages%2fic%2f832x468%2fp01hz772.jpg/"
        },
        "episode": -1,
        "fanart": "",
        "file": "plugin://plugin.video.iplayerwww/?url=https%3A%2F%2Fwww.bbc.co.uk%2Fiplayer%2Fepisodes%2Fp00db1jf%2Fzoo-quest&mode=128&name=%5BB%5DZoo+Quest%5B%2FB%5D&iconimage=https%3A%2F%2Fichef.bbci.co.uk%2Fimages%2Fic%2F832x468%2Fp01hz772.jpg&description=David+Attenborough+searches+for+one+of+the+rarest+animals+of+Madagascar%2C+the+indri.+%281961%29&subtitles_url=&logged_in=False",
        "filetype": "directory",
        "label": "[B]Zoo Quest[/B]",
        "season": -1,
        "showtitle": "",
        "title": "[B]Zoo Quest[/B]",
        "type": "unknown",
        "year": 0
    }
```

Some data can be added by the devs, when creating the lists with the folders in the addon.

For now it's not possible to add support, unfortunately, if the addon is updated and becomes more standardized, I can review it.

**Comment by luizoti** [comment]
Closing this issue.
