### ISSUE TITLE
Ability to add a Shared (smb) folder as a custom managed folder

### ISSUE THREAD

**Issue by airam84** [luizoti/script.library.integration.tool#30]
Hi,

I'm trying to setup my Kodi on a mysql server and I have only 1 issue to make it work. When I try to add an smb path as a custom managed folder, I get an error when LIT tries to configure the managed folder.

Is it possible to add this feature so I am able to setup Kodi as a media server? Otherwise I would have to manually configure LIT on each Kodi installation...very time consuming! lol

**Comment by luizoti** [comment]
So, as I recall, the original implementation (and I haven't changed much from that) makes the whole process of dealing with the file system directly using python, the problem is you can't deal with smb, the solution would be to rewrite the whole thing the filesystem module to use kodi's built-in solutions (if i have read and understood) kodi would be able to handle smb without problems.

This has already been requested on the kodi forum, I started to analyze this possibility, but I lack time to do tests and changes.

If one day I succeed, I do, otherwise the community could send a PR, but they're not so keen.

**Comment by luizoti** [comment]
> Hi,
> 
> I'm trying to setup my Kodi on a mysql server and I have only 1 issue to make it work. When I try to add an smb path as a custom managed folder, I get an error when LIT tries to configure the managed folder.
> 
> Is it possible to add this feature so I am able to setup Kodi as a media server? Otherwise I would have to manually configure LIT on each Kodi installation...very time consuming! lol

I was successful in rewriting lit to use KODI's internal module relating to the filesystem, now it supports SMB directories, the problem currently is relating to the database, sqlite does not support samba, if you find a solution, perfect, otherwise, perhaps the database remains local.

Regarding mysql, don't get your hopes up for anything about this anytime soon, I don't even know where to start, maybe an option to choose which bank to use, but I don't have any knowledge in mysql server, so it will take a while.

**Comment by luizoti** [comment]
Well, by my tests from the 0.8.34 version it is possible to use SMB and other forms of network disk, according to the support that kodi itself provides, but LIT has a sqlite3 database (local), so when trying to use it will return an error, in the future I will try to implement a SQL database with this it will be possible to have everything running centralized on a remote server.

Clossing this issue.
